project:
  type: website
  output-dir: docs
website:
  title: "YouTube Performance Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Documentation.qmd
        text: Documentation
      - href: Tutorial.qmd
        text: Tutorial
      - href: TechnicalReport.qmd
        text: Technical Report
format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true



